from enum import StrEnum


class ApiErrorCode(StrEnum):
    BANK_NOT_FOUND = "BANK_NOT_FOUND"
    BANK_DETAILS_NOT_FOUND = "BANK_DETAILS_NOT_FOUND"
    BRANCH_NOT_FOUND = "BRANCH_NOT_FOUND"
    BRANCH_DETAILS_NOT_FOUND = "BRANCH_DETAILS_NOT_FOUND"
    BANK_EMPLOYEE_NOT_FOUND = "BANK_EMPLOYEE_NOT_FOUND"
    BANK_EMPLOYEE_DETAILS_NOT_FOUND = "BANK_EMPLOYEE_DETAILS_NOT_FOUND"
    
    BANK_EMPLOYEE_ALREADY_EXISTS = "BANK_EMPLOYEE_ALREADY_EXISTS"
  
    APPRAISER_NOT_FOUND = "APPRAISER_NOT_FOUND"
    APPRAISER_DETAILS_NOT_FOUND = "APPRAISER_DETAILS_NOT_FOUND"
    APPRAISER_HAS_SERVICES = "APPRAISER_HAS_SERVICES"
    APPRAISER_NO_ACTIVE_SERVICES = "APPRAISER_NO_ACTIVE_SERVICES"

    REAPPRAISAL_SERVICE_NOT_FOUND = "REAPPRAISAL_SERVICE_NOT_FOUND"
    REAPPRAISAL_SERVICE_DETAILS_NOT_FOUND = "REAPPRAISAL_SERVICE_DETAILS_NOT_FOUND"

    REAPPRAISAL_SERVICE_REIMBURSEMENT_NOT_FOUND = (
        "REAPPRAISAL_SERVICE_REIMBURSEMENT_NOT_FOUND"
    )
    REAPPRAISAL_SERVICE_REIMBURSEMENT_DETAILS_NOT_FOUND = (
        "REAPPRAISAL_SERVICE_REIMBURSEMENT_DETAILS_NOT_FOUND"
    )
    REAPPRAISAL_SERVICE_ADVANCE_NOT_FOUND = "REAPPRAISAL_SERVICE_ADVANCE_NOT_FOUND"
    REAPPRAISAL_SERVICE_ADVANCE_DETAILS_NOT_FOUND = (
        "REAPPRAISAL_SERVICE_ADVANCE_DETAILS_NOT_FOUND"
    )
    FILE_NOT_FOUND = "FILE_NOT_FOUND"
    PAYOUT_CYCLE_NOT_FOUND = "PAYOUT_CYCLE_NOT_FOUND"
    PAYOUT_CYCLE_DETAILS_NOT_FOUND = "PAYOUT_CYCLE_DETAILS_NOT_FOUND"

    PAYOUT_STATEMENT_NOT_FOUND = "PAYOUT_STATEMENT_NOT_FOUND"
    PAYOUT_STATEMENT_DETAILS_NOT_FOUND = "PAYOUT_STATEMENT_DETAILS_NOT_FOUND"
    DATA_ALREADY_EXITS = "DATA_ALREADY_EXITS"
    REAPPRAISAL_SERVICE_CHARGE_SETTLEMENT_NOT_FOUND = (
        "REAPPRAISAL_SERVICE_CHARGE_SETTLEMENT_NOT_FOUND"
    )
    REAPPRAISAL_SERVICE_CHARGE_SETTLEMENT_DETAILS_NOT_FOUND = (
        "REAPPRAISAL_SERVICE_CHARGE_SETTLEMENT_DETAILS_NOT_FOUND"
    )

    ADVANCE_SETTLEMENT_NOT_FOUND = "ADVANCE_SETTLEMENT_NOT_FOUND"
    ADVANCE_SETTLEMENT_DETAILS_NOT_FOUND = "ADVANCE_SETTLEMENT_DETAILS_NOT_FOUND"

    REAPPRAISAL_SERVICE_REIMBURSEMENT_SETTLEMENT_NOT_FOUND = (
        "REAPPRAISAL_SERVICE_REIMBURSEMENT_SETTLEMENT_NOT_FOUND"
    )
    REAPPRAISAL_SERVICE_REIMBURSEMENT_SETTLEMENT_DETAILS_NOT_FOUND = (
        "REAPPRAISAL_SERVICE_REIMBURSEMENT_SETTLEMENT_DETAILS_NOT_FOUND"
    )
    REAPPRAISAL_SERVICE_CHARGE_SETTLEMENT_STATUS_ALREADY_EXISTS = (
        "REAPPRAISAL_SERVICE_CHARGE_SETTLEMENT_STATUS_ALREADY_EXISTS"
    )
    REAPPRAISAL_SERVICE_INVALID_SETTLEMENT_STATUS = (
        "REAPPRAISAL_SERVICE_INVALID_SETTLEMENT_STATUS"
    )
    REAPPRAISAL_SERVICE_ADVANCE_SETTLEMENT_STATUS_ALREADY_EXISTS = (
        "REAPPRAISAL_SERVICE_ADVANCE_SETTLEMENT_STATUS_ALREADY_EXISTS"
    )
    REAPPRAISAL_SERVICE_REIMBURSEMENT_SETTLEMENT_STATUS_ALREADY_EXISTS = (
        "REAPPRAISAL_SERVICE_REIMBURSEMENT_SETTLEMENT_STATUS_ALREADY_EXISTS"
    )
    REAPPRAISAL_SERVICE_SETTLEMENT_STATUS_ALREADY_EXISTS = (
        "REAPPRAISAL_SERVICE_SETTLEMENT_STATUS_ALREADY_EXISTS"
    )
    REAPPRAISAL_SERVICE_BRANCH_ID_NOT_FOUND = "REAPPRAISAL_SERVICE_BRANCH_ID_NOT_FOUND"
    DETAILS_NOT_FOUND = "DETAILS_NOT_FOUND"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    BAD_REQUEST = "BAD_REQUEST"
    DUPLICATE_ENTRY = "DUPLICATE_ENTRY"

    REAPPRAISAL_SERVICE_FILE_PENDING = "REAPPRAISAL_SERVICE_FILE_PENDING"
    REAPPRAISAL_SERVICE_INVALID_STATUS = "REAPPRAISAL_SERVICE_INVALID_STATUS"
    REAPPRAISAL_SERVICE_DATE_INCORRECT = "REAPPRAISAL_SERVICE_DATE_INCORRECT"
    REAPPRAISAL_SERVICE_DELETE_NOT_ALLOWED = "REAPPRAISAL_SERVICE_DELETE_NOT_ALLOWED"
