# fly.toml app configuration file generated for gbauction on 2025-10-24T15:49:19+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gbauction'
primary_region = 'bom'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[checks]
  [checks.health]
    type = "http"
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/docs"
