name: Deploy to Fly.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Fly.io
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Copy root .env to lambda/phobos for deployment
        run: |
          # Copy root .env to lambda/phobos directory
          cp .env lambda/phobos/.env
          echo ".env file copied for deployment"

      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only --config lambda/phobos/fly.toml
        working-directory: lambda/phobos
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Deployment status
        run: |
          echo "Deployment complete!"
          echo "App URL: https://gbauction.fly.dev"
          echo "View logs: flyctl logs --app gbauction"
